name: Build GeoNetwork 5 docker image and push to ghcr.io

on:
  push:
    branches: [ "feature/multi-architecture-build" ]
  pull_request:
    branches: [ "feature/multi-architecture-build" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Build and Push Multi-arch Docker image
        if: github.event_name == 'push'
        env:
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/gn5-main"
          
          mvn spring-boot:build-image \
            -pl src/apps/geonetwork \
            -Dspring-boot.build-image.imageName=${IMAGE_NAME}:${{ github.sha }} \
            -Dspring-boot.build-image.platforms=linux/amd64,linux/arm64 \
            -Dspring-boot.build-image.publish=true \
            -Dspring-boot.build-image.docker.publishRegistry.username=${REGISTRY_USERNAME} \
            -Dspring-boot.build-image.docker.publishRegistry.password=${REGISTRY_TOKEN} \
            -Dspring-boot.build-image.docker.publishRegistry.url=ghcr.io
          
          # Also tag and push as latest
          mvn spring-boot:build-image \
            -pl src/apps/geonetwork \
            -Dspring-boot.build-image.imageName=${IMAGE_NAME}:latest \
            -Dspring-boot.build-image.platforms=linux/amd64,linux/arm64 \
            -Dspring-boot.build-image.publish=true \
            -Dspring-boot.build-image.docker.publishRegistry.username=${REGISTRY_USERNAME} \
            -Dspring-boot.build-image.docker.publishRegistry.password=${REGISTRY_TOKEN} \
            -Dspring-boot.build-image.docker.publishRegistry.url=ghcr.io

      - name: Build Docker image (PR only - single arch)
        if: github.event_name == 'pull_request'
        run: |
          mvn spring-boot:build-image \
            -pl src/apps/geonetwork \
            -Dspring-boot.build-image.imageName=gn5-main:${{ github.sha }}