name: Build GeoNetwork 5 docker image and push to ghcr.io

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Build Docker image with Spring Boot
        run: |
          mvn spring-boot:build-image \
            -pl src/apps/geonetwork \
            -Dspring-boot.build-image.imageName=gn5-main:${{ github.sha }}

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Docker image
        if: github.event_name == 'push'
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/gn5-main"
          
          # Tag with commit SHA
          docker tag gn5-main:${{ github.sha }} ${IMAGE_NAME}:${{ github.sha }}
          
          # Tag with 'latest'
          docker tag gn5-main:${{ github.sha }} ${IMAGE_NAME}:latest
          
          # Push both tags
          docker push ${IMAGE_NAME}:${{ github.sha }}
          docker push ${IMAGE_NAME}:latest